### ISSUE TITLE
Lego Power Functions lights are not supported

### ISSUE THREAD

**Issue by filippsudanov** [itdaniher/WeDoMore#12]
Lego lights is a couple of LEDs, that also work with WeDo USB hub (https://shop.lego.com/en-US/LEGO-Power-Functions-Light-8870). They are supported by Lego software on Windows.

Would be nice to add support for this.

**Comment by cpseager** [comment]
Its trivial to do yourself, just add two more numbers (203, 204) in as valid motor IDs.

https://github.com/itdaniher/WeDoMore/issues/7

**Comment by itdaniher** [comment]
Hey! I haven't seen the LEDs before, probably a new device from LEGO? If someone makes a simple PR for this I'll happily merge it, or I'll do so myself when I find a few moments.

Thanks!
